export default {'quiz1':
  [{'id': 1, 'image': 'images/Q1q1.png', 'Answer': 'A good silencer and exhaust system'},
    {'id': 2, 'image': 'images/Q1q2.png', 'Answer': '10pm to 5am'},
    {'id': 3, 'image': 'images/Q1q3.png', 'Answer': '4 metres'},
    {'id': 4, 'image': 'images/Q1q4.png', 'Answer': 'that the vehicle was roadworthy at the time of checking'},
    {'id': 5, 'image': 'images/Q1q5.png', 'Answer': 'sway from side to side'},
    {'id': 6, 'image': 'images/Q1q6.png', 'Answer': '90km/h'},
    {'id': 7, 'image': 'images/Q1q7.png', 'Answer': 'False'},
    {'id': 8, 'image': 'images/Q1q8.png', 'Answer': 'Brake smoothly and move over to the left side of the road'},
    {'id': 9, 'image': 'images/Q1q9.png', 'Answer': 'True'},
    {'id': 10, 'image': 'images/Q1q10.png', 'Answer': '3 metres from the front edge of the front seat'},
    {'id': 11, 'image': 'images/Q1q11.png', 'Answer': 'Yes'},
    {'id': 12, 'image': 'images/Q1q12.png', 'Answer': 'No'},
    {'id': 13, 'image': 'images/Q1q13.png', 'Answer': 'No'},
    {'id': 14, 'image': 'images/Q1q14.png', 'Answer': 'No'},
    {'id': 15, 'image': 'images/Q1q15.png', 'Answer': 'Yes'},
    {'id': 16, 'image': 'images/Q1q16.png', 'Answer': 'When both signs have been pulled in'},
    {'id': 17, 'image': 'images/Q1q17.png', 'Answer': 'You may turn right'},
    {'id': 18, 'image': 'images/Q1q18.png', 'Answer': 'Turning vehicles drive straight over all road markings and wait to turn right'},
    {'id': 19, 'image': 'images/Q1q19.png', 'Answer': 'Stop and wait until it changes to a green light'},
    {'id': 20, 'image': 'images/Q1q20.png', 'Answer': 'Do not drive faster than 50km/h'},
    {'id': 21, 'image': 'images/Q1q21.png', 'Answer': 'Slow down so that you can look both ways to check that the crossing is clear'},
    {'id': 22, 'image': 'images/Q1q22.png', 'Answer': 'Give way to pedestrians on any part of the crossing'},
    {'id': 23, 'image': 'images/Q1q23.png', 'Answer': 'following other vehicles'},
    {'id': 24, 'image': 'images/Q1q24.png', 'Answer': 'Stay stopped until the lights stop flashing'},
    {'id': 25, 'image': 'images/Q1q25.png', 'Answer': 'failing to supply your correct name and address'},
    {'id': 26, 'image': 'images/Q1q26.png', 'Answer': 'You may not stop your vehicle at any time'},
    {'id': 27, 'image': 'images/Q1q27.png', 'Answer': '100 metres'},
    {'id': 28, 'image': 'images/Q1q28.png', 'Answer': 'Be careful and apply the give way rules'},
    {'id': 29, 'image': 'images/Q1q29.png', 'Answer': 'When it is operating its siren or flashing lights'},
    {'id': 30, 'image': 'images/Q1q30.png', 'Answer': 'Stop and check to see if anyone is hurt'},
    {'id': 31, 'image': 'images/Q1q31.png', 'Answer': 'The right-hand lane'},
    {'id': 32, 'image': 'images/Q1q32.png', 'Answer': 'A'},
    {'id': 33, 'image': 'images/Q1q33.png', 'Answer': 'Move to the left side of the road and turn when the road is clear'},
    {'id': 34, 'image': 'images/Q1q34.png', 'Answer': 'Pull over and stop to use the cellphone when it is safe to do so'},
    {'id': 35, 'image': 'images/Q1q35.png', 'Answer': 'True'},
    {'id': 36, 'image': 'images/Q1q36.png', 'Answer': 'have a red light at the back'},
    {'id': 37, 'image': 'images/Q1q37.png', 'Answer': 'True'},
    {'id': 38, 'image': 'images/Q1q38.png', 'Answer': '1.5mm'},
    {'id': 39, 'image': 'images/Q1q39.png', 'Answer': 'A moped'},
    {'id': 40, 'image': 'images/Q1q40.png', 'Answer': 'False'},
    {'id': 41, 'image': 'images/Q1q41.png', 'Answer': '30 minutes after sunset until 30 minutes before sunrise'},
    {'id': 42, 'image': 'images/Q1q42.png', 'Answer': 'Yes'},
    {'id': 43, 'image': 'images/Q1q43.png', 'Answer': 'A pedestrian crossing ahead'},
    {'id': 44, 'image': 'images/Q1q44.png', 'Answer': 'Come to a complete stop'},
    {'id': 45, 'image': 'images/Q1q45.png', 'Answer': '20km/h'},
    {'id': 46, 'image': 'images/Q1q46.png', 'Answer': 'B'},
    {'id': 47, 'image': 'images/Q1q47.png', 'Answer': 'Do not drive faster than 100km/h'},
    {'id': 48, 'image': 'images/Q1q48.png', 'Answer': 'have someone stay with the vehicle who can move it'},
    {'id': 49, 'image': 'images/Q1q49.png', 'Answer': 'Slow down and stop'},
    {'id': 50, 'image': 'images/Q1q50.png', 'Answer': '6 metres'},
    {'id': 51, 'image': 'images/Q1q51.png', 'Answer': 'Slow down and check for any oncoming vehicles before driving on'},
    {'id': 52, 'image': 'images/Q1q52.png', 'Answer': 'True'},
    {'id': 53, 'image': 'images/Q1q53.png', 'Answer': 'sweep it up straight away if you can do so safely'},
    {'id': 54, 'image': 'images/Q1q54.png', 'Answer': 'Pull over to the left and giveway to the vehicle coming up the hill'},
    {'id': 55, 'image': 'images/Q1q55.png', 'Answer': 'slow down, move off the road gradually, stop and turn your vehicle hazard lights on'},
    {'id': 56, 'image': 'images/Q1q56.png', 'Answer': 'Check your blindspots before moving left'},
    {'id': 57, 'image': 'images/Q1q57.png', 'Answer': 'A police officer'},
    {'id': 58, 'image': 'images/Q1q58.png', 'Answer': 'Let 1 vehicle in and then go'},
    {'id': 59, 'image': 'images/Q1q14.png', 'Answer': 'stay back until the cyclist has passed the intersection'}
  ]
}
